# Conf of Goliath, the humongously small OIDC & OAuth authorization
# server

answer = "42"
[server]
port = "8000"

[tokens]
# Reference to
# https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us
signing_key = "all your keys are belong to us"
