# Conf of Goliath, the humongously small OIDC & OAuth authorization
# server

answer = "42"

[server]
port = "8000"

[app]
client_id = "goliath-client-id"
client_secret = "Over the Hills and Far Away"
allowed_redirect_uris = [
  "http://localhost:8000/callback",
  "https://example.com/callback"
]

[token]
# Reference to
# https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us
signing_key = "all your keys are belong to us"

# Access token expiry, 2h
access_token_exp_ms = 7200000
# Refresh token expiry, 2h
refresh_token_exp_ms = 7200000
# ID token expiry, 2h
id_token_exp_ms = 7200000
