// OAuth specific parts of Goliath
//
// Author: torstein
package iam

import "crypto/rand"

// The server side code parameter comes from the OAuth2 spec,
// it's generated by the server
func GenerateServerCode() string {
	return rand.Text()
}
